export const ELEMENTOS = [
    [
        { name: "Hidrógeno", ab: "H", En: 2.1, nA: 1, color: "purple" },
        { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null },
        { name: "Helio", ab: "He", En: null, nA: 2, color: "deep-purple" },
    ],
    [
        { name: "Litio", ab: "Li", En: 1.0, nA: 3, color: "light-blue" },
        { name: "Berilio", ab: "Be", En: 1.5, nA: 4, color: "blue" },
        { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null },
        { name: "Boro", ab: "B", En: 2.0, nA: 5, color: "red" },
        { name: "Carnono", ab: "C", En: 2.5, nA: 6, color: "purple" },
        { name: "Nitrógeno", ab: "N", En: 3.0, nA: 7, color: "purple" },
        { name: "Oxígeno", ab: "O", En: 3.5, nA: 8, color: "purple" },
        { name: "Fluourita", ab: "F", En: 4.0, nA: 9, color: "indigo" },
        { name: "Neón", ab: "Ne", En: null, nA: 10, color: "deep-purple" },
    ],
    [
        { name: "Sodio", ab: "Na", En: 0.9, nA: 11, color: "light-blue" },
        { name: "Magnesio", ab: "Mg", En: 1.2, nA: 12, color: "blue" },
        { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null }, { isNull: null },
        { name: "Aluminio", ab: "Al", En: 1.5, nA: 13, color: "orange" },
        { name: "Silicio", ab: "Si", En: 1.8, nA: 14, color: "red" },
        { name: "Fósforo", ab: "P", En: 2.1, nA: 15, color: "purple" },
        { name: "Azufre", ab: "S", En: 2.5, nA: 16, color: "purple" },
        { name: "Cloro", ab: "Cl", En: 3.0, nA: 17, color: "indigo" },
        { name: "Argón", ab: "Ar", En: null, nA: 18, color: "deep-purple" },
    ],
    [
        { name: "Potasio", ab: "K", En: 0.8, nA: 19, color: "light-blue" },
        { name: "Calcio", ab: "Ca", En: 1.0, nA: 20, color: "blue" },
        { name: "Escancio", ab: "Sc", En: 1.3, nA: 21, color: "black" },
        { name: "Titanio", ab: "Ti", En: 1.5, nA: 22, color: "black" },
        { name: "Vanadio", ab: "V", En: 1.6, nA: 23, color: "black" },
        { name: "Cromo", ab: "Cr", En: 1.6, nA: 24, color: "black" },
        { name: "Manganeso", ab: "Mn", En: 1.5, nA: 25, color: "black" },
        { name: "Hierro", ab: "Fe", En: 1.8, nA: 26, color: "black" },
        { name: "Cobalto", ab: "Co", En: 1.9, nA: 27, color: "black" },
        { name: "Niquel", ab: "Ni", En: 1.9, nA: 28, color: "black" },
        { name: "Cobre", ab: "Cu", En: 1.9, nA: 29, color: "black" },
        { name: "Cinc", ab: "Zn", En: 1.2, nA: 30, color: "black" },
        { name: "Galio", ab: "Ga", En: 1.6, nA: 31, color: "orange" },
        { name: "Germani", ab: "Ge", En: 1.6, nA: 32, color: "red" },
        { name: "Arsénico", ab: "As", En: 1.8, nA: 33, color: "red" },
        { name: "Selenio", ab: "Se", En: 2.0, nA: 34, color: "purple" },
        { name: "Bromo", ab: "Br", En: 2.4, nA: 35, color: "indigo" },
        { name: "Criptón", ab: "Kr", En: null, nA: 36, color: "deep-purple" },
    ],
    [
        { name: "Rubidio", ab: "Rb", En: 0.8, nA: 37, color: "light-blue" },
        { name: "Estroncio", ab: "Sr", En: 1.0, nA: 38, color: "blue" },
        { name: "Itrio", ab: "Y", En: 1.2, nA: 39, color: "black" },
        { name: "Circonio", ab: "Zr", En: 1.4, nA: 40, color: "black" },
        { name: "Niobio", ab: "Nb", En: 1.6, nA: 41, color: "black" },
        { name: "Molibdeno", ab: "Mo", En: 1.8, nA: 42, color: "black" },
        { name: "Tecnecio", ab: "Tc", En: 1.9, nA: 43, color: "black" },
        { name: "Ruterio", ab: "Ru", En: 2.2, nA: 44, color: "black" },
        { name: "Rhodium", ab: "Rh", En: 2.2, nA: 45, color: "black" },
        { name: "Paladio", ab: "Pd", En: 2.2, nA: 46, color: "black" },
        { name: "Plata", ab: "Ag", En: 1.9, nA: 47, color: "black" },
        { name: "Cadmio", ab: "Cd", En: 1.7, nA: 48, color: "black" },
        { name: "Indio", ab: "In", En: 1.7, nA: 49, color: "orange" },
        { name: "Estaño", ab: "Sn", En: 1.8, nA: 50, color: "orange" },
        { name: "Antimorio", ab: "Sb", En: 1.9, nA: 51, color: "red" },
        { name: "Telurio", ab: "Te", En: 2.1, nA: 52, color: "red" },
        { name: "Yodo", ab: "I", En: 2.5, nA: 53, color: "indigo" },
        { name: "Xenón", ab: "Xe", En: null, nA: 54, color: "deep-purple" },
    ],
    [
        { name: "Cesio", ab: "Cs", En: 0.7, nA: 55, color: "light-blue" },
        { name: "Bario", ab: "Ba", En: 0.9, nA: 56, color: "blue" },
        { name: "Lutecio", ab: "Lu", En: null, nA: 71, color: "teal" },
        { name: "Hafnio", ab: "Hf", En: 1.3, nA: 72, color: "black" },
        { name: "Tantalio", ab: "Ta", En: 1.5, nA: 73, color: "black" },
        { name: "Tungsteno", ab: "W", En: 1.7, nA: 74, color: "black" },
        { name: "Renio", ab: "Re", En: 1.9, nA: 75, color: "black" },
        { name: "Osmio", ab: "Os", En: 2.2, nA: 76, color: "black" },
        { name: "Iridio", ab: "Ir", En: 2.2, nA: 77, color: "black" },
        { name: "Platino", ab: "Pt", En: 2.2, nA: 78, color: "black" },
        { name: "Oro", ab: "Au", En: 2.4, nA: 79, color: "black" },
        { name: "Mercurio", ab: "Hg", En: 1.9, nA: 80, color: "black" },
        { name: "Talio", ab: "Tl", En: 1.8, nA: 81, color: "orange" },
        { name: "Plomo", ab: "Pb", En: 1.9, nA: 82, color: "orange" },
        { name: "Bismuto", ab: "Bi", En: 1.9, nA: 83, color: "orange" },
        { name: "Polonio", ab: "Po", En: 2.0, nA: 84, color: "orange" },
        { name: "Astato", ab: "At", En: 2.2, nA: 85, color: "red" },
        { name: "Radón", ab: "Rn", En: null, nA: 86, color: "deep-purple" },
    ],
    [
        { name: "Francio", ab: "Fr", En: 0.7, nA: 87, color: "light-blue" },
        { name: "Radio", ab: "Ra", En: 0.7, nA: 88, color: "blue" },
        { name: "Laurencio", ab: "Lr", En: null, nA: 103, color: "lime" },
        { name: "Rutherfordio", ab: "Rf", En: null, nA: 104, color: "black" },
        { name: "Dubnio", ab: "Db", En: null, nA: 105, color: "black" },
        { name: "Seaborgio", ab: "Sg", En: null, nA: 106, color: "black" },
        { name: "Bohrio", ab: "Bh", En: null, nA: 107, color: "black" },
        { name: "Hasio", ab: "Hs", En: null, nA: 108, color: "black" },
        { name: "Meitnerio", ab: "Mt", En: null, nA: 109, color: "black" },
        { name: "Darmstatio", ab: "Ds", En: null, nA: 110, color: "black" },
        { name: "Roentgenio", ab: "Rg", En: null, nA: 111, color: "black" },
        { name: "Copérnico", ab: "Cn", En: null, nA: 112, color: "black" },
        { name: "Nihonio", ab: "Nh", En: null, nA: 113, color: "orange" },
        { name: "Flerovio", ab: "Fl", En: null, nA: 114, color: "orange" },
        { name: "Moscovio", ab: "Mc", En: null, nA: 115, color: "orange" },
        { name: "Livermorio", ab: "Lv", En: null, nA: 116, color: "orange" },
        { name: "Teneso", ab: "Ts", En: null, nA: 117, color: "indigo" },
        { name: "Oganesón", ab: "Og", En: null, nA: 118, color: "deep-purple" },
    ],
]